# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_user_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='programming_language',
            field=models.TextField(default=''),
        ),
    ]
