# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_auto_20180524_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='difficult',
            new_name='difficulty',
        ),
    ]
