# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_auto_20180524_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='python', max_length=20),
        ),
    ]
